module Closures
export local_Ri_ν_convectivetanh_shearlinear, local_Ri_κ_convectivetanh_shearlinear
export nonlocal_Ri_ν_convectivetanh_shearlinear, nonlocal_Ri_κ_convectivetanh_shearlinear
export local_Ri_ν_convectivetanh_shearlinear_2Pr, local_Ri_κ_convectivetanh_shearlinear_2Pr

include("base_closure.jl")
end